spring:
  application.name: order-processing
  profiles.active: test
management:
  endpoints.web:
    base-path: /
    exposure.include: health,info,metrics,mappings
  endpoint.health.show-details: when-authorized
---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:orders_db;DB_CLOSE_DELAY=-1
    username: sa
    password: sa