version: '2.1'
services:
  activemq:
    container_name: activemq
    image: rmohr/activemq:5.15.6-alpine
    ports:
      - "61616:61616"
    networks: [order-processing-kata-network]
  order-receipt:
    container_name: order-receipt
    image: order-receipt:latest
    environment:
      SPRING_APPLICATION_JSON: '{"spring":{"profiles":{"active":"production"}}}'
    expose:
      - 8080
    ports:
      - 8080:8080
    networks: [order-processing-kata-network]
    links:
      - activemq:activemq
    depends_on:
      - activemq
networks:
  order-processing-kata-network:
    driver: bridge