version: '3.7'
services:
  activemq:
    container_name: activemq
    image: rmohr/activemq:5.15.6-alpine
    expose:
      - 61616
    ports:
      - 8161:8161
    networks: [order-processing-kata-network]
  h2:
    container_name: h2
    image: oscarfonts/h2:alpine
    expose:
      - 1521
    ports:
      - 8081:81
    networks: [order-processing-kata-network]
  flyway:
    container_name: flyway
    image: boxfuse/flyway:5.2.1-alpine
    command: -url=jdbc:h2:tcp://h2:1521/opt/h2-data/orders_db -user=sa -password=sa migrate
    volumes:
      - ./db/migration:/flyway/sql
    networks: [order-processing-kata-network]
    depends_on:
      - h2
  order-receipt:
    container_name: order-receipt
    image: order-receipt:latest
    ports:
      - 8080:8080
    networks: [order-processing-kata-network]
    depends_on:
      - h2
      - activemq
    environment:
      JAVA_OPTS: '-noverify -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap'
      SPRING_CONFIG_LOCATION: 'file:///app/resources/application.yml,file:///app/resources/application-activemq.yml,file:///app/resources/application-h2.yml,file:///app/resources/application-jms.yml,file:///app/resources/application-management.yml,file:///app/resources/application-orders.yml'
      SPRING_PROFILES_ACTIVE: 'production'
      SPRING_DATASOURCE_URL: 'jdbc:h2:tcp://h2:1521/opt/h2-data/orders_db;DB_CLOSE_DELAY=-1'
      SPRING_ACTIVEMQ_BROKER_URL: 'tcp://activemq:61616'
  order-placement:
    container_name: order-placement
    image: order-placement:latest
    networks: [order-processing-kata-network]
    depends_on:
      - h2
      - activemq
    environment:
      JAVA_OPTS: '-noverify -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap'
      SPRING_CONFIG_LOCATION: 'file:///app/resources/application.yml,file:///app/resources/application-activemq.yml,file:///app/resources/application-h2.yml,file:///app/resources/application-jms.yml,file:///app/resources/application-orders.yml'
      SPRING_PROFILES_ACTIVE: 'production'
      SPRING_DATASOURCE_URL: 'jdbc:h2:tcp://h2:1521/opt/h2-data/orders_db;DB_CLOSE_DELAY=-1'
      SPRING_ACTIVEMQ_BROKER_URL: 'tcp://activemq:61616'
  order-report:
    container_name: order-report
    image: order-report:latest
    ports:
      - 8000:8080
    networks: [order-processing-kata-network]
    depends_on:
      - h2
      - activemq
    environment:
      JAVA_OPTS: '-noverify -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap'
      SPRING_CONFIG_LOCATION: 'file:///app/resources/application.yml,file:///app/resources/application-activemq.yml,file:///app/resources/application-h2.yml,file:///app/resources/application-jms.yml,file:///app/resources/application-management.yml,file:///app/resources/application-orders.yml'
      SPRING_PROFILES_ACTIVE: 'production'
      SPRING_DATASOURCE_URL: 'jdbc:h2:tcp://h2:1521/opt/h2-data/orders_db;DB_CLOSE_DELAY=-1'
      SPRING_ACTIVEMQ_BROKER_URL: 'tcp://activemq:61616'
networks:
  order-processing-kata-network:
    driver: bridge