version: '3.7'
services:
  activemq:
    container_name: activemq
    image: rmohr/activemq:5.15.6-alpine
    expose:
      - 61616
    ports:
      - 8161:8161
#    healthcheck:
#      test: ["CMD", "curl", "-f", "-u", "admin:admin", "http://localhost:8161/admin/xml/queues.jsp"]
#      interval: 1m30s
#      timeout: 10s
#      start_period: 30s
#      retries: 3
    networks: [order-processing-kata-network]
  h2:
    container_name: h2
    image: oscarfonts/h2:alpine
    expose:
      - 1521
    ports:
      - 8081:81
    networks: [order-processing-kata-network]
  order-receipt:
    container_name: order-receipt
    image: order-receipt:latest
    expose:
      - 8080
    ports:
      - 8080:8080
    networks: [order-processing-kata-network]
    depends_on:
      - h2
      - activemq
    links:
      - h2:h2.local
      - activemq:activemq.local
    environment:
      SPRING_PROFILES_ACTIVE: production
      SPRING_DATASOURCE_URL: 'jdbc:h2:tcp://h2.local:1521/mem:orders_db;DB_CLOSE_DELAY=-1'
      SPRING_ACTIVEMQ_BROKER_URL: 'tcp://activemq.local:61616'
  order-placement:
    container_name: order-placement
    image: order-placement:latest
    networks: [order-processing-kata-network]
    depends_on:
      - activemq
    links:
      - activemq:activemq.local
    environment:
      SPRING_PROFILES_ACTIVE: 'production'
      SPRING_ACTIVEMQ_BROKER_URL: 'tcp://activemq.local:61616'
networks:
  order-processing-kata-network:
    driver: bridge