spring:
  application.name: order-placement
  profiles.active: test
  profiles.include:
    - activemq
#    - h2
    - jms
#    - management
    - orders
---
spring:
  profiles: test
  activemq:
    broker-url: vm://embedded?broker.persistent=false,useShutdownHook=false
---
spring:
  profiles: production
  activemq:
    user: admin
    password: password
    in-memory: false
    broker-url: tcp://172.19.0.3:61616