spring:
  application.name: order-placement
  profiles.active: test
  profiles.include:
    - activemq
    - jms
    - orders
---
spring:
  profiles: test
  activemq:
    broker-url: vm://embedded?broker.persistent=false,useShutdownHook=false
---
spring:
  profiles: production
  activemq:
    user: admin
    password: password
    in-memory: false
    broker-url: tcp://localhost:61616