spring:
  application.name: order-placement
  flyway.enabled: false
  jmx.enabled: false
  profiles.active: test
  profiles.include:
    - activemq
    - postgres
    - jms
    - orders
---
spring:
  profiles: test
  datasource:
    url: jdbc:postgresql://localhost:5432/test_order_placement
  activemq:
    broker-url: vm://embedded?broker.persistent=false,useShutdownHook=false
    pool.idle-timeout: 0s
---
spring:
  profiles: production
  datasource:
    url: jdbc:postgresql://postgres:5432/orders_db
  activemq:
    user: admin
    password: password
    in-memory: false
    broker-url: tcp://localhost:61616