spring:
  application.name: order-receipt
  profiles.active: test
  profiles.include:
    - activemq
    - h2
    - jms
    - management
    - orders
---
spring:
  profiles: test
  datasource:
    url: jdbc:h2:mem:orders_db;DB_CLOSE_DELAY=-1
  activemq:
    broker-url: vm://embedded?broker.persistent=false,useShutdownHook=false
---
spring:
  profiles: production
  datasource:
    url: jdbc:h2:tcp://172.19.0.2:1521/mem:orders_db;DB_CLOSE_DELAY=-1
  activemq:
    user: admin
    password: password
    in-memory: false
    broker-url: tcp://172.19.0.3:61616