spring:
  application.name: order-processing
  profiles.active: test
  profiles.include:
    - h2
    - jms
    - activemq
    - management
---
spring:
  profiles: test
  activemq:
    broker-url: vm://embedded?broker.persistent=false,useShutdownHook=false
---
spring:
  profiles: production
  activemq:
    user: admin
    password: password
    in-memory: false
    broker-url: tcp://172.19.0.2:61616