spring.security.user:
  name: admin
  password: s3C4E7
management:
  endpoints.web:
    base-path: /management
    exposure.include: health,info,metrics,mappings,caches
  endpoint.health.show-details: WHEN_AUTHORIZED