CREATE TABLE event_store (
  event_id BIGINT AUTO_INCREMENT PRIMARY KEY,
  timestamp TIMESTAMP NOT NULL,
  handle VARCHAR(64) NOT NULL,
  aggregate_id VARCHAR(64) NOT NULL,
  payload CLOB NOT NULL
);

COMMIT;